# Generated by Django 5.1.7 on 2025-03-26 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctorapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/PatientProfilePic/')),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=20)),
                ('symptoms', models.TextField()),
                ('admit_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to='doctorapp.doctor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='patientapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDischargeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('symptoms', models.TextField(null=True)),
                ('admit_date', models.DateField(auto_now_add=True)),
                ('release_date', models.DateField()),
                ('days_spent', models.PositiveIntegerField()),
                ('room_charge', models.PositiveIntegerField()),
                ('medicine_cost', models.PositiveIntegerField()),
                ('doctor_fee', models.PositiveIntegerField()),
                ('other_charge', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharged_patients', to='doctorapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_details', to='patientapp.patient')),
            ],
        ),
    ]
