# Generated by Django 5.1.7 on 2025-04-09 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientapp', '0002_alter_patient_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20, unique=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('assigned_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('ward', models.CharField(choices=[('General', 'General Ward'), ('ICU', 'Intensive Care Unit'), ('Emergency', 'Emergency Ward'), ('Pediatric', 'Pediatric Ward'), ('Maternity', 'Maternity Ward')], default='General', max_length=50)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_beds', to='patientapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('Moderate', 'Moderate'), ('Mild', 'Mild')], max_length=50)),
                ('description', models.TextField()),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_cases', to='patientapp.patient')),
            ],
        ),
    ]
